clear, clc, close all;


[CONFIG_strParams] = CONFIG_setConfigParams();

[DPREP_strData.mFeatures, DPREP_strData.mTargets] = DCONV_convert(CONFIG_strParams.fullRawDataFileName);

[DPREP_strData.mTestFeatures, DPREP_strData.mTestTargets, DPREP_strData.mTrainFeatures, DPREP_strData.mTrainTargets] =... 
    TTS_formTrainTestSets(DPREP_strData.mFeatures,...
                          DPREP_strData.mTargets,...
                          CONFIG_strParams.sSplitCriteria,...
                          CONFIG_strParams.nTrainToTestFactor);

load auto_label.mat new_labels; 
DPREP_strData.mAutoLabels = new_labels;

[DPREP_strData.mTrainBatchTargets, DPREP_strData.mTrainBatchData, DPREP_strData.mTestBatchTargets, DPREP_strData.mTestBatchData] =... 
    BM_makeBatches(DPREP_strData.mTestFeatures,...
                   DPREP_strData.mTestTargets,...
                   DPREP_strData.mTrainFeatures,...
                   DPREP_strData.mTrainTargets,...
                   CONFIG_strParams.nMaxFeaturesRange,...
                   CONFIG_strParams.bAutoLabel,...
                   DPREP_strData.mAutoLabels,...
                   CONFIG_strParams.nBatchSize);
               
LM_startLearningProcess(CONFIG_strParams,...
                        DPREP_strData.mTrainBatchTargets, DPREP_strData.mTrainBatchData, DPREP_strData.mTestBatchTargets, DPREP_strData.mTestBatchData);